### ISSUE TITLE
Issue Compiling

### ISSUE THREAD

**Issue by plasticocelot123** [doldecomp/sms#39]
I tried to compile the program using msys2, but every time it gives me this error: make: /bin/powerpc-eabi-as.exe: No such file or directory. make: *** [Makefile:158: build/sms.jp.r0/asm/JSystem/JKRArchivePri.o] Error 127. Can you fix that?

**Comment by RevoSucks** [comment]
Please read the README.md. DevkitPRO needs to be installed.

**Comment by ThePlayerRolo** [comment]
> Please read the README.md. DevkitPRO needs to be installed.

devKitPro? in my decomp? /j
